//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt_45
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карт доступ.
    /// </summary>
    // *** Start programmer edit section *** (КартДоступ CustomAttributes)

    // *** End programmer edit section *** (КартДоступ CustomAttributes)
    [AutoAltered()]
    [Caption("База Данных")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартДоступE", new string[] {
            "СправСотр as \'Фио сотрудника\'",
            "СправСотр.Фио as \'Фио сотрудника\'",
            "СправСотр.СправДолж.Должность as \'Должность\'"})]
    [AssociatedDetailViewAttribute("КартДоступE", "БазаДанных", "БазаДанныхE", true, "", "База Данных", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("КартДоступE", "СправСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио сотрудника")]
    [View("КартДоступL", new string[] {
            "СправСотр.Фио as \'Фио сотрудника\'",
            "СправСотр.СправДолж.Должность as \'Должность\'"})]
    public class КартДоступ : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Proekt_45.СправСотр fСправСотр;
        
        private IIS.Proekt_45.DetailArrayOfБазаДанных fБазаДанных;
        
        // *** Start programmer edit section *** (КартДоступ CustomMembers)

        // *** End programmer edit section *** (КартДоступ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.Дата CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.Дата Get start)

                // *** End programmer edit section *** (КартДоступ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (КартДоступ.Дата Get end)

                // *** End programmer edit section *** (КартДоступ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.Дата Set start)

                // *** End programmer edit section *** (КартДоступ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (КартДоступ.Дата Set end)

                // *** End programmer edit section *** (КартДоступ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Карт доступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.СправСотр CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.СправСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СправСотр"})]
        [NotNull()]
        public virtual IIS.Proekt_45.СправСотр СправСотр
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get start)
                IIS.Proekt_45.СправСотр result = this.fСправСотр;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set start)
                this.fСправСотр = value;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set end)
            }
        }
        
        /// <summary>
        /// Карт доступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.БазаДанных CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.БазаДанных CustomAttributes)
        public virtual IIS.Proekt_45.DetailArrayOfБазаДанных БазаДанных
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.БазаДанных Get start)

                // *** End programmer edit section *** (КартДоступ.БазаДанных Get start)
                if ((this.fБазаДанных == null))
                {
                    this.fБазаДанных = new IIS.Proekt_45.DetailArrayOfБазаДанных(this);
                }
                IIS.Proekt_45.DetailArrayOfБазаДанных result = this.fБазаДанных;
                // *** Start programmer edit section *** (КартДоступ.БазаДанных Get end)

                // *** End programmer edit section *** (КартДоступ.БазаДанных Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.БазаДанных Set start)

                // *** End programmer edit section *** (КартДоступ.БазаДанных Set start)
                this.fБазаДанных = value;
                // *** Start programmer edit section *** (КартДоступ.БазаДанных Set end)

                // *** End programmer edit section *** (КартДоступ.БазаДанных Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартДоступE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступE", typeof(IIS.Proekt_45.КартДоступ));
                }
            }
            
            /// <summary>
            /// "КартДоступL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступL", typeof(IIS.Proekt_45.КартДоступ));
                }
            }
        }
    }
}
